hugoVersion:
  extended: true
  min: "0.91.2"

imports:
- path: github.com/bep/hugo-starter-tailwind-basic/v2
- path: github.com/team-durumi/tailwind-aa-theme
- path: github.com/team-durumi/hugo-search-fuse-js-aa
- path: github.com/gohugoio/hugo-mod-heroicons
