title: 정의기억연대
baseURL: https://wwm-dev.netlify.app

languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true
paginate: 12

build:
  writeStats: true

googleAnalytics:

taxonomies:
  tag: tags
