title: 전쟁과여성인권박물관
baseURL: https://stage.womenandwarmuseum.net

languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true

build:
  writeStats: true

googleAnalytics:

taxonomies:
  tag: tags