# themeNoPipe: true

title: 전쟁과여성인권박물관
description: 전쟁과여성인권박물관 홈페이지에 오신것을 환영합니다.
images:
  - img/site-feature-image.png

license:
  title_of_work: 전쟁과여성인권박물관
  link_to_work: https://www.womenandwarmuseum.net/
  createor_of_work: 팀두루미
  link_to_creator_profile: https://durumi.io
  year_of_creation: 2021  

featuredImages:
  - image1.png
  - image2.jpg

googleFonts:
  - https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@200&display=swap
  - https://fonts.googleapis.com/css2?family=Gothic+A1:wght@300;700&display=swap
