# 스티비 API https://api.stibee.com/docs/
# @install humao.rest-client

# 구독 폼 화면 https://page.stibee.com/subscriptions/152880
### 특정 주소록에 구독자 추가
POST https://page.stibee.com/api/v1.0/lists/152880 HTTP/1.1
accept: application/json
content-type: application/json

{
  "email": "dev@mozo.kr",
  "termsOfServiceAgreed": true
}

## response
# {
#   "code": "Succeed.List.Confirm.NonPaid",
#   "httpStatusCode": 200,
#   "message": " 입력하신 이메일 주소(dev@mozo.kr)로 확인 메일을 보내드렸습니다.",
#   "listName": "dev"
# }

### 구독 발송 메일 목록 받아오기
GET https://stibee.com/api/v1.0/feeds HTTP/1.1
accept: application/json
content-type: application/json
AccessToken: {{ stbAccessToken }}

listId=112752&opts=statistics&sortBy=created_time&offset=0&limit=10

# listId: 112752
# opts: statistics
# sortBy: created_time
# offset: 0
# limit: 10
